### PR TITLE
Add table of content

### PR DESCRIPTION
**Pull request by alexbaumgertner**
Model doc page is very long, I think, with TOC it will be much more convenient :)

PS:
TOC will be added in https://github.com/balderdashy/waterline-docs/pull/71

### CODE REVIEW

**Comment by dmarcelino** [comment]
Hi @alexbaumgertner, thanks for this. For now it's best we wait for @eddieajau's PR #71 to go in as it refactors the whole docs.

**Comment by alexbaumgertner** [comment]
@dmarcelino Oh, great news for everyone :+1:

**Comment by dmarcelino** [comment]
@alexbaumgertner, are you OK with the current TOC introduced in PR #71? Closing this for now.

**Comment by alexbaumgertner** [comment]
Ok, thanks!

**Pull request closed without merging**
