### PR TITLE
Added findOrCreate to the documentation

### PR DESCRIPTION
**Pull request by Globegitter**
This is based on https://github.com/balderdashy/waterline/pull/845 and as mentioned in https://github.com/balderdashy/waterline-docs/issues/9

Let me know if you want anything changed/improved, etc.

### CODE REVIEW

**Comment by tjwebb** [comment]
@mikermcneil @particlebanana I think we should merge this

**Comment by devinivy** [comment]
I think that comments were added to the wrong example.  I found this under the `find` docs.
 ```javascript
User.find({ name: 'Walter Jr' })
.exec(function(err, users) {
//either user(s) with the name 'Walter Jr' get returned or
//a single user gets created with the name 'Walter Jr' and returned
});
```

Past that, this looks good.

**Comment by Globegitter** [comment]
@devinivy thanks for catching - just fixed.

**Comment by devinivy** [comment]
@tjwebb just said that `findOrCreate` requires two arguments here: https://github.com/balderdashy/waterline/issues/609#issuecomment-85040899 .  Can someone verify that?  If so, this needs to be revised.  If not, that thread needs clarification.

**Comment by Globegitter** [comment]
@devinivy Since https://github.com/balderdashy/waterline/pull/845 got merged in it it does support the syntax I describe.

**Comment by tjwebb** [comment]
It doesn't "require" two arguments on its own; but if you have required fields, as in balderdashy/waterline#609, then having the second argument be `undefined` will not pass any of your required attribute checks.

**Comment by devinivy** [comment]
Cool–sounds like we're all set.  Thanks!

**Pull request merged**
