### PR TITLE
Added docs about .query method

### PR DESCRIPTION
**Pull request by Globegitter**
Since I was using it today thought it would be useful. Let me know id anything is missing.

### CODE REVIEW

**Comment by devinivy** [comment]
Thanks!  Two things
1. I think sails-mysql returns the rows directly in `results`.  Maybe we should highlight that the format of `results` is dependent on the underlying database wrapper.  And perhaps we should standardize the `results` fomat with a breaking change in 0.11 (reflected in docs and SQL interface tests).
2. There's a tiny markdown typo (missing `]`) around the sails-postgresql link.

**Comment by Globegitter** [comment]
Thanks for pointing out @devinivy Should be both fixed now. And yep I agree standardising that for 0.11 would imo be worth the breaking change.

**Comment by devinivy** [comment]
:heavy_check_mark: looks good to me!  @tjwebb / @dmarcelino ?

**Comment by tjwebb** [comment]
Thanks @Globegitter !

**Pull request merged**
